# Generated by Django 4.1.5 on 2023-01-14 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=8, verbose_name='Номер группы')),
                ('first_name', models.CharField(max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('is_ready', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='products.product', verbose_name='Продукты')),
            ],
        ),
    ]
